services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - redis_network
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data

networks:
  redis_network:
    name: redis_network